2024-06-18 15:42:00 | INFO | model_worker | args: Namespace(host='localhost', port=41002, worker_address='http://localhost:41002', controller_address='http://localhost:41001', model_path='/home/c205/workspace/models/HuatuoGPT2-13B/', revision='main', device='cuda', gpus=None, num_gpus=2, max_gpu_memory=None, dtype=None, load_8bit=False, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, enable_exllama=False, exllama_max_seq_len=4096, exllama_gpu_split=None, exllama_cache_8bit=False, enable_xft=False, xft_max_seq_len=4096, xft_dtype=None, model_names=None, conv_template=None, embed_in_truncate=False, limit_worker_concurrency=5, stream_interval=2, no_register=False, seed=None, debug=False, ssl=False)
2024-06-18 15:42:00 | INFO | model_worker | Loading the model ['HuatuoGPT2-13B'] on worker 3912aff4 ...
2024-06-18 15:42:03 | ERROR | stderr | Traceback (most recent call last):
2024-06-18 15:42:03 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-18 15:42:03 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/model_worker.py", line 414, in <module>
2024-06-18 15:42:03 | ERROR | stderr |     args, worker = create_model_worker()
2024-06-18 15:42:03 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/model_worker.py", line 385, in create_model_worker
2024-06-18 15:42:03 | ERROR | stderr |     worker = ModelWorker(
2024-06-18 15:42:03 | ERROR | stderr |              ^^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/model_worker.py", line 77, in __init__
2024-06-18 15:42:03 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-06-18 15:42:03 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/model/model_adapter.py", line 362, in load_model
2024-06-18 15:42:03 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-06-18 15:42:03 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/model/model_adapter.py", line 108, in load_model
2024-06-18 15:42:03 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2024-06-18 15:42:03 | ERROR | stderr |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
2024-06-18 15:42:03 | ERROR | stderr |     return model_class.from_pretrained(
2024-06-18 15:42:03 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 670, in from_pretrained
2024-06-18 15:42:03 | ERROR | stderr |     return super(BaichuanForCausalLM, cls).from_pretrained(pretrained_model_name_or_path, *model_args,
2024-06-18 15:42:03 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3754, in from_pretrained
2024-06-18 15:42:03 | ERROR | stderr |     ) = cls._load_pretrained_model(
2024-06-18 15:42:03 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/transformers/modeling_utils.py", line 4214, in _load_pretrained_model
2024-06-18 15:42:03 | ERROR | stderr |     new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
2024-06-18 15:42:03 | ERROR | stderr |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/transformers/modeling_utils.py", line 887, in _load_state_dict_into_meta_model
2024-06-18 15:42:03 | ERROR | stderr |     set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
2024-06-18 15:42:03 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat-for-huatuo/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 400, in set_module_tensor_to_device
2024-06-18 15:42:03 | ERROR | stderr |     new_value = value.to(device)
2024-06-18 15:42:03 | ERROR | stderr |                 ^^^^^^^^^^^^^^^^
2024-06-18 15:42:03 | ERROR | stderr | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB. GPU
