2024-06-13 20:25:03 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8000, controller_address='0.0.0.0:21001', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_keys=None, ssl=False)
2024-06-13 20:25:03 | ERROR | stderr | INFO:     Started server process [3213245]
2024-06-13 20:25:03 | ERROR | stderr | INFO:     Waiting for application startup.
2024-06-13 20:25:03 | ERROR | stderr | INFO:     Application startup complete.
2024-06-13 20:25:03 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2024-06-13 20:40:52 | INFO | stdout | INFO:     127.0.0.1:37292 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:40:52 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:40:52 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:40:52 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:40:52 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     raise exc
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:40:52 | ERROR | stderr |     raise exc
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:40:52 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:40:52 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:40:52 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:40:52 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:40:52 | ERROR | stderr |     raise exc
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:40:52 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:40:52 | ERROR | stderr |     response = await func(request)
2024-06-13 20:40:52 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:40:52 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:40:52 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:40:52 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:40:52 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 414, in create_chat_completion
2024-06-13 20:40:52 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:40:52 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:40:52 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:40:52 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:40:52 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:40:52 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:40:52 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:40:52 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:40:52 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:40:52 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:40:52 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:40:52 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:40:52 | INFO | stdout | INFO:     127.0.0.1:37308 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:40:52 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:40:52 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:40:52 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:40:52 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     raise exc
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:40:52 | ERROR | stderr |     raise exc
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:40:52 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:40:52 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:40:52 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:40:52 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:40:52 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:40:52 | ERROR | stderr |     raise exc
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:40:52 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:40:52 | ERROR | stderr |     response = await func(request)
2024-06-13 20:40:52 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:40:52 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:40:52 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:40:52 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:40:52 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 414, in create_chat_completion
2024-06-13 20:40:52 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:40:52 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:40:52 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:40:52 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:40:52 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:40:52 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:40:52 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:40:52 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:40:52 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:40:52 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:40:52 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:40:52 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:40:52 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:40:54 | INFO | stdout | INFO:     127.0.0.1:37312 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:40:54 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:40:54 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:40:54 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:40:54 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:40:54 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:40:54 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:40:54 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:40:54 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:40:54 | ERROR | stderr |     raise exc
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:40:54 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:40:54 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:40:54 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:40:54 | ERROR | stderr |     raise exc
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:40:54 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:40:54 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:40:54 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:40:54 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:40:54 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:40:54 | ERROR | stderr |     raise exc
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:40:54 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:40:54 | ERROR | stderr |     response = await func(request)
2024-06-13 20:40:54 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:40:54 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:40:54 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:40:54 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:40:54 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 414, in create_chat_completion
2024-06-13 20:40:54 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:40:54 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:40:54 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:40:54 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:40:54 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:40:54 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:40:54 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:40:54 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:40:54 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:40:54 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:40:54 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:40:54 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:40:54 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:52:19 | INFO | stdout | INFO:     127.0.0.1:51548 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:52:19 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:52:19 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:52:19 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:52:19 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:52:19 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:52:19 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:52:19 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:52:19 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:52:19 | ERROR | stderr |     raise exc
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:52:19 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:52:19 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:52:19 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:52:19 | ERROR | stderr |     raise exc
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:52:19 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:52:19 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:52:19 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:52:19 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:52:19 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:52:19 | ERROR | stderr |     raise exc
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:52:19 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:52:19 | ERROR | stderr |     response = await func(request)
2024-06-13 20:52:19 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:52:19 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:52:19 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:52:19 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:52:19 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:52:19 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:52:19 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:52:19 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:52:19 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:52:19 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:52:19 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:52:19 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:52:19 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:52:19 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:52:19 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:52:19 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:52:19 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:52:19 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:52:20 | INFO | stdout | INFO:     127.0.0.1:51552 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:52:20 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:52:20 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:52:20 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:52:20 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:52:20 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:52:20 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:52:20 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:52:20 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:52:20 | ERROR | stderr |     raise exc
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:52:20 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:52:20 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:52:20 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:52:20 | ERROR | stderr |     raise exc
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:52:20 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:52:20 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:52:20 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:52:20 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:52:20 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:52:20 | ERROR | stderr |     raise exc
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:52:20 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:52:20 | ERROR | stderr |     response = await func(request)
2024-06-13 20:52:20 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:52:20 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:52:20 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:52:20 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:52:20 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:52:20 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:52:20 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:52:20 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:52:20 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:52:20 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:52:20 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:52:20 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:52:20 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:52:20 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:52:20 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:52:20 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:52:20 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:52:20 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:52:21 | INFO | stdout | INFO:     127.0.0.1:51564 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:52:21 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:52:21 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:52:21 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:52:21 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:52:21 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:52:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:52:21 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:52:21 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:52:21 | ERROR | stderr |     raise exc
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:52:21 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:52:21 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:52:21 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:52:21 | ERROR | stderr |     raise exc
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:52:21 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:52:21 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:52:21 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:52:21 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:52:21 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:52:21 | ERROR | stderr |     raise exc
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:52:21 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:52:21 | ERROR | stderr |     response = await func(request)
2024-06-13 20:52:21 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:52:21 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:52:21 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:52:21 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:52:21 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:52:21 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:52:21 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:52:21 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:52:21 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:52:21 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:52:21 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:52:21 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:52:21 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:52:21 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:52:21 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:52:21 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:52:21 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:52:21 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:53:15 | INFO | stdout | INFO:     127.0.0.1:38578 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:53:15 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:53:15 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:53:15 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:53:15 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:53:15 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:53:15 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:53:15 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:53:15 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:53:15 | ERROR | stderr |     raise exc
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:53:15 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:53:15 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:53:15 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:15 | ERROR | stderr |     raise exc
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:15 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:53:15 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:53:15 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:53:15 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:53:15 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:15 | ERROR | stderr |     raise exc
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:15 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:53:15 | ERROR | stderr |     response = await func(request)
2024-06-13 20:53:15 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:53:15 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:53:15 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:53:15 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:53:15 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:53:15 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:53:15 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:53:15 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:53:15 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:53:15 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:53:15 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:53:15 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:53:15 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:53:15 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:53:15 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:53:15 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:53:15 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:53:15 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:53:16 | INFO | stdout | INFO:     127.0.0.1:38590 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:53:16 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:53:16 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:53:16 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:53:16 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:53:16 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:53:16 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:53:16 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:53:16 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:53:16 | ERROR | stderr |     raise exc
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:53:16 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:53:16 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:53:16 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:16 | ERROR | stderr |     raise exc
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:16 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:53:16 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:53:16 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:53:16 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:53:16 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:16 | ERROR | stderr |     raise exc
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:16 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:53:16 | ERROR | stderr |     response = await func(request)
2024-06-13 20:53:16 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:53:16 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:53:16 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:53:16 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:53:16 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:53:16 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:53:16 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:53:16 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:53:16 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:53:16 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:53:16 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:53:16 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:53:16 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:53:16 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:53:16 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:53:16 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:53:16 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:53:16 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:53:18 | INFO | stdout | INFO:     127.0.0.1:38602 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:53:18 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:53:18 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:53:18 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:53:18 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:53:18 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:53:18 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:53:18 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:53:18 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:53:18 | ERROR | stderr |     raise exc
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:53:18 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:53:18 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:53:18 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:18 | ERROR | stderr |     raise exc
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:18 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:53:18 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:53:18 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:53:18 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:53:18 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:18 | ERROR | stderr |     raise exc
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:18 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:53:18 | ERROR | stderr |     response = await func(request)
2024-06-13 20:53:18 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:53:18 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:53:18 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:53:18 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:53:18 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:53:18 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:53:18 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:53:18 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:53:18 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:53:18 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:53:18 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:53:18 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:53:18 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:53:18 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:53:18 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:53:18 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:53:18 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:53:18 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:53:47 | INFO | stdout | INFO:     127.0.0.1:42028 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:53:47 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:53:47 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:53:47 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:53:47 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:53:47 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:53:47 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:53:47 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:53:47 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:53:47 | ERROR | stderr |     raise exc
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:53:47 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:53:47 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:53:47 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:47 | ERROR | stderr |     raise exc
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:47 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:53:47 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:53:47 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:53:47 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:53:47 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:47 | ERROR | stderr |     raise exc
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:47 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:53:47 | ERROR | stderr |     response = await func(request)
2024-06-13 20:53:47 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:53:47 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:53:47 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:53:47 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:53:47 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:53:47 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:53:47 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:53:47 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:53:47 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:53:47 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:53:47 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:53:47 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:53:47 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:53:47 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:53:47 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:53:47 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:53:47 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:53:47 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:53:48 | INFO | stdout | INFO:     127.0.0.1:42042 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:53:48 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:53:48 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:53:48 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:53:48 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:53:48 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:53:48 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:53:48 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:53:48 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:53:48 | ERROR | stderr |     raise exc
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:53:48 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:53:48 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:53:48 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:48 | ERROR | stderr |     raise exc
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:48 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:53:48 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:53:48 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:53:48 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:53:48 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:48 | ERROR | stderr |     raise exc
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:48 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:53:48 | ERROR | stderr |     response = await func(request)
2024-06-13 20:53:48 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:53:48 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:53:48 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:53:48 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:53:48 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:53:48 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:53:48 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:53:48 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:53:48 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:53:48 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:53:48 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:53:48 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:53:48 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:53:48 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:53:48 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:53:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:53:48 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:53:48 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:53:50 | INFO | stdout | INFO:     127.0.0.1:42050 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:53:50 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:53:50 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:53:50 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:53:50 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:53:50 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:53:50 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:53:50 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:53:50 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:53:50 | ERROR | stderr |     raise exc
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:53:50 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:53:50 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:53:50 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:50 | ERROR | stderr |     raise exc
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:50 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:53:50 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:53:50 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:53:50 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:53:50 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:53:50 | ERROR | stderr |     raise exc
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:53:50 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:53:50 | ERROR | stderr |     response = await func(request)
2024-06-13 20:53:50 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:53:50 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:53:50 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:53:50 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:53:50 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:53:50 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:53:50 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:53:50 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:53:50 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:53:50 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:53:50 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:53:50 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:53:50 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:53:50 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:53:50 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:53:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:53:50 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:53:50 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:54:45 | INFO | stdout | INFO:     127.0.0.1:49876 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:54:45 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:54:45 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:54:45 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:54:45 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:54:45 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:54:45 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:54:45 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:54:45 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:54:45 | ERROR | stderr |     raise exc
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:54:45 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:54:45 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:54:45 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:54:45 | ERROR | stderr |     raise exc
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:54:45 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:54:45 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:54:45 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:54:45 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:54:45 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:54:45 | ERROR | stderr |     raise exc
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:54:45 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:54:45 | ERROR | stderr |     response = await func(request)
2024-06-13 20:54:45 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:54:45 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:54:45 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:54:45 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:54:45 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:54:45 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:54:45 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:54:45 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:54:45 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:54:45 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:54:45 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:54:45 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:54:45 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:54:45 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:54:45 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:54:45 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:54:45 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:54:45 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:54:46 | INFO | stdout | INFO:     127.0.0.1:50090 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:54:46 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:54:46 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:54:46 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:54:46 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:54:46 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:54:46 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:54:46 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:54:46 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:54:46 | ERROR | stderr |     raise exc
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:54:46 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:54:46 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:54:46 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:54:46 | ERROR | stderr |     raise exc
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:54:46 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:54:46 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:54:46 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:54:46 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:54:46 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:54:46 | ERROR | stderr |     raise exc
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:54:46 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:54:46 | ERROR | stderr |     response = await func(request)
2024-06-13 20:54:46 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:54:46 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:54:46 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:54:46 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:54:46 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:54:46 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:54:46 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:54:46 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:54:46 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:54:46 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:54:46 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:54:46 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:54:46 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:54:46 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:54:46 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:54:46 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:54:46 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:54:46 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
2024-06-13 20:54:48 | INFO | stdout | INFO:     127.0.0.1:50092 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
2024-06-13 20:54:48 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-06-13 20:54:48 | ERROR | stderr | Traceback (most recent call last):
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-06-13 20:54:48 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-06-13 20:54:48 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-06-13 20:54:48 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-06-13 20:54:48 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-06-13 20:54:48 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-06-13 20:54:48 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-06-13 20:54:48 | ERROR | stderr |     raise exc
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-06-13 20:54:48 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-06-13 20:54:48 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-06-13 20:54:48 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:54:48 | ERROR | stderr |     raise exc
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:54:48 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-06-13 20:54:48 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-06-13 20:54:48 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-06-13 20:54:48 | ERROR | stderr |     await self.app(scope, receive, send)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-06-13 20:54:48 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-06-13 20:54:48 | ERROR | stderr |     raise exc
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-06-13 20:54:48 | ERROR | stderr |     await app(scope, receive, sender)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-06-13 20:54:48 | ERROR | stderr |     response = await func(request)
2024-06-13 20:54:48 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-06-13 20:54:48 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-06-13 20:54:48 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-06-13 20:54:48 | ERROR | stderr |     return await dependant.call(**values)
2024-06-13 20:54:48 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 544, in create_completion
2024-06-13 20:54:48 | ERROR | stderr |     error_check_ret = await check_model(request)
2024-06-13 20:54:48 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 146, in check_model
2024-06-13 20:54:48 | ERROR | stderr |     models = await fetch_remote(controller_address + "/list_models", None, "models")
2024-06-13 20:54:48 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/openai_api_server.py", line 75, in fetch_remote
2024-06-13 20:54:48 | ERROR | stderr |     async with session.post(url, json=pload) as response:
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
2024-06-13 20:54:48 | ERROR | stderr |     self._resp = await self._coro
2024-06-13 20:54:48 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client.py", line 548, in _request
2024-06-13 20:54:48 | ERROR | stderr |     req = self._request_class(
2024-06-13 20:54:48 | ERROR | stderr |           ^^^^^^^^^^^^^^^^^^^^
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 327, in __init__
2024-06-13 20:54:48 | ERROR | stderr |     self.update_host(url)
2024-06-13 20:54:48 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 401, in update_host
2024-06-13 20:54:48 | ERROR | stderr |     raise InvalidURL(url)
2024-06-13 20:54:48 | ERROR | stderr | aiohttp.client_exceptions.InvalidURL: 0.0.0.0:21001/list_models
